vich_uploader:
    db_driver: orm

    mappings:
        currency_icon:
            uri_prefix: /images/currency
            upload_destination: '%kernel.project_dir%/public/images/currency'
            namer:  vich_uploader.namer_uniqid